/**
 * songs.js
 *
 * The app's songs
 */

window.songs = [
  {
    songId: "SID-13423453",
    artistId: "AID-000001",
    title: "Love Story",
    released: 2008,
    duration: 230,
    url: "https://www.youtube.com/watch?v=8xg3vE8Ie_E",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423454",
    artistId: "AID-000001",
    title: "You Belong with Me",
    released: 2008,
    duration: 230,
    url: "https://www.youtube.com/watch?v=VuNIsY6JdUw",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423455",
    artistId: "AID-000001",
    title: "Shake It Off",
    released: 2014,
    duration: 242,
    url: "https://www.youtube.com/watch?v=nfWlot6h_JM",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423456",
    artistId: "AID-000001",
    title: "Blank Space",
    released: 2014,
    duration: 231,
    url: "https://www.youtube.com/watch?v=e-ORhEE9VVg",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423457",
    artistId: "AID-000001",
    title: "Bad Blood",
    released: 2014,
    duration: 210,
    url: "https://www.youtube.com/watch?v=QcIy9NiNbmo",
    isExplicit: true,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423458",
    artistId: "AID-000001",
    title: "Look What You Made Me Do",
    released: 2017,
    duration: 211,
    url: "https://www.youtube.com/watch?v=3tmd-ClpJxA",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423459",
    artistId: "AID-000001",
    title: "Delicate",
    released: 2017,
    duration: 230,
    url: "https://www.youtube.com/watch?v=tCXGJQYZ9JA",
    isExplicit: true,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423460",
    artistId: "AID-000001",
    title: "Cardigan",
    released: 2020,
    duration: 240,
    url: "https://www.youtube.com/watch?v=zLSUp53y-HQ",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423461",
    artistId: "AID-000001",
    title: "Willow",
    released: 2020,
    duration: 217,
    url: "https://www.youtube.com/watch?v=7EvwIw4gIyk",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423462",
    artistId: "AID-000001",
    title: "We Are Never Ever Getting Back Together",
    released: 2012,
    duration: 193,
    url: "https://www.youtube.com/watch?v=WA4iX5D9Z64",
    isExplicit: true,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423463",
    artistId: "AID-000001",
    title: "I Knew You Were Trouble",
    released: 2012,
    duration: 220,
    url: "https://www.youtube.com/watch?v=vNoKguSdy4Y",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423464",
    artistId: "AID-000001",
    title: "Wildest Dreams",
    released: 2014,
    duration: 231,
    url: "https://www.youtube.com/watch?v=IdneKLhsWOQ",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423465",
    artistId: "AID-000001",
    title: "Style",
    released: 2014,
    duration: 231,
    url: "https://www.youtube.com/watch?v=-CmadmM5cOk",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423466",
    artistId: "AID-000001",
    title: "Mine",
    released: 2010,
    duration: 231,
    url: "https://www.youtube.com/watch?v=oxNLRqMJMZk",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423467",
    artistId: "AID-000001",
    title: "Red",
    released: 2012,
    duration: 231,
    url: "https://www.youtube.com/watch?v=Zlot0i3Zykw",
    isExplicit: true,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423468",
    artistId: "AID-000001",
    title: "22",
    released: 2012,
    duration: 231,
    url: "https://www.youtube.com/watch?v=AgFeZr5ptV8",
    isExplicit: true,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423469",
    artistId: "AID-000001",
    title: "All Too Well",
    released: 2012,
    duration: 611,
    url: "https://www.youtube.com/watch?v=sRxrwjOtIag",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423470",
    artistId: "AID-000001",
    title: "Enchanted",
    released: 2010,
    duration: 231,
    url: "https://www.youtube.com/watch?v=igIfiqqVHtA",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423471",
    artistId: "AID-000001",
    title: "Back to December",
    released: 2010,
    duration: 231,
    url: "https://www.youtube.com/watch?v=QUwxKWT6m7U",
    isExplicit: false,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  {
    songId: "SID-13423472",
    artistId: "AID-000001",
    title: "Begin Again",
    released: 2012,
    duration: 231,
    url: "https://www.youtube.com/watch?v=cMPEd8m79Hw",
    isExplicit: true,
    imageUrl: "./image/Taylor-Swift-Song.jpeg",
  },
  // Charlie Puth
  {
    songId: "SID-000021",
    artistId: "AID-000002",
    title: "Attention",
    released: 2017,
    duration: 213,
    url: "https://www.youtube.com/watch?v=nfs8NYg7yQM",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000022",
    artistId: "AID-000002",
    title: "We Don't Talk Anymore",
    released: 2016,
    duration: 230,
    url: "https://www.youtube.com/watch?v=3AtDnEC4zak",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000023",
    artistId: "AID-000002",
    title: "See You Again",
    released: 2015,
    duration: 229,
    url: "https://www.youtube.com/watch?v=RgKAFK5djSk",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000024",
    artistId: "AID-000002",
    title: "One Call Away",
    released: 2015,
    duration: 215,
    url: "https://www.youtube.com/watch?v=BxuY9FET9Y4",
    isExplicit: true,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000025",
    artistId: "AID-000002",
    title: "Marvin Gaye",
    released: 2015,
    duration: 211,
    url: "https://www.youtube.com/watch?v=igNVdlXhKcI",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000026",
    artistId: "AID-000002",
    title: "How Long",
    released: 2017,
    duration: 210,
    url: "https://www.youtube.com/watch?v=CwfoyVa980U",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000027",
    artistId: "AID-000002",
    title: "The Way I Am",
    released: 2018,
    duration: 195,
    url: "https://www.youtube.com/watch?v=EQnk-h-LCpQ",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000028",
    artistId: "AID-000002",
    title: "Done for Me",
    released: 2018,
    duration: 187,
    url: "https://www.youtube.com/watch?v=3tYajkHNK58",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000029",
    artistId: "AID-000002",
    title: "Mother",
    released: 2019,
    duration: 182,
    url: "https://www.youtube.com/watch?v=jTMzLbz9_r0",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000030",
    artistId: "AID-000002",
    title: "Girlfriend",
    released: 2020,
    duration: 193,
    url: "https://www.youtube.com/watch?v=asYfhMHAgqs",
    isExplicit: true,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000031",
    artistId: "AID-000002",
    title: "I Warned Myself",
    released: 2019,
    duration: 172,
    url: "https://www.youtube.com/watch?v=wjIes1eGAw4",
    isExplicit: true,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000032",
    artistId: "AID-000002",
    title: "Cheating on You",
    released: 2019,
    duration: 198,
    url: "https://www.youtube.com/watch?v=fOoSbUoayQE",
    isExplicit: true,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000033",
    artistId: "AID-000002",
    title: "Patient",
    released: 2018,
    duration: 200,
    url: "https://www.youtube.com/watch?v=uKmA0nHe4no",
    isExplicit: true,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000034",
    artistId: "AID-000002",
    title: "Dangerously",
    released: 2016,
    duration: 192,
    url: "https://www.youtube.com/watch?v=TBXQu8ORnBQ",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000035",
    artistId: "AID-000002",
    title: "BOY",
    released: 2018,
    duration: 185,
    url: "https://www.youtube.com/watch?v=iILJvqrAQ_w",
    isExplicit: true,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000036",
    artistId: "AID-000002",
    title: "LA Girls",
    released: 2018,
    duration: 201,
    url: "https://www.youtube.com/watch?v=iW3Than5jrs",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000037",
    artistId: "AID-000002",
    title: "Up All Night",
    released: 2016,
    duration: 205,
    url: "https://www.youtube.com/watch?v=vBLQFGHtSzg",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000038",
    artistId: "AID-000002",
    title: "Change",
    released: 2018,
    duration: 188,
    url: "https://www.youtube.com/watch?v=e9XbKS9xWD0",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  {
    songId: "SID-000039",
    artistId: "AID-000002",
    title: "Hard On Yourself",
    released: 2020,
    duration: 180,
    url: "https://www.youtube.com/watch?v=bRAS8T6j3pM",
    isExplicit: false,
    imageUrl: "./image/charlie-puth-song.jpg",
  },
  // Justin Bieber's Songs
  {
    songId: "SID-000041",
    artistId: "AID-000003",
    title: "Sorry",
    released: 2015,
    duration: 200,
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-000042",
    artistId: "AID-000003",
    title: "Love Yourself",
    released: 2015,
    duration: 233,
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  // Justtin Bieber

  {
    songId: "SID-001",
    artistId: "AID-000003",
    title: "Sorry",
    released: 2015,
    duration: 200,
    url: "https://www.youtube.com/watch?v=fRh_vgS2dFE",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-002",
    artistId: "AID-000003",
    title: "Love Yourself",
    released: 2015,
    duration: 233,
    url: "https://www.youtube.com/watch?v=oyEuk8j8imI",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-003",
    artistId: "AID-000003",
    title: "What Do You Mean?",
    released: 2015,
    duration: 208,
    url: "https://www.youtube.com/watch?v=DK_0jXPuIr0",
    isExplicit: true,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-004",
    artistId: "AID-000003",
    title: "Baby",
    released: 2010,
    duration: 214,
    url: "https://www.youtube.com/watch?v=kffacxfA7G4",
    isExplicit: true,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-005",
    artistId: "AID-000003",
    title: "Yummy",
    released: 2020,
    duration: 210,
    url: "https://www.youtube.com/watch?v=EaMed9sUPVo",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-006",
    artistId: "AID-000003",
    title: "Intentions",
    released: 2020,
    duration: 231,
    url: "https://www.youtube.com/watch?v=3AyMjyHu1bA",
    isExplicit: true,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-007",
    artistId: "AID-000003",
    title: "Peaches",
    released: 2021,
    duration: 198,
    url: "https://www.youtube.com/watch?v=tQ0yjYUFKAE",
    isExplicit: true,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-008",
    artistId: "AID-000003",
    title: "Holy",
    released: 2020,
    duration: 212,
    url: "https://www.youtube.com/watch?v=pvPsJFRGleA",
    isExplicit: true,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-009",
    artistId: "AID-000003",
    title: "Lonely",
    released: 2020,
    duration: 140,
    url: "https://www.youtube.com/watch?v=xQOO2xGQ1Pc",
    isExplicit: true,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-010",
    artistId: "AID-000003",
    title: "Ghost",
    released: 2021,
    duration: 156,
    url: "https://www.youtube.com/watch?v=Fp8msa5uYsc",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-011",
    artistId: "AID-000003",
    title: "Anyone",
    released: 2021,
    duration: 183,
    url: "https://www.youtube.com/watch?v=KIK3azN4w34",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-012",
    artistId: "AID-000003",
    title: "Company",
    released: 2016,
    duration: 203,
    url: "https://www.youtube.com/watch?v=gdx7gN1UyX0",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-013",
    artistId: "AID-000003",
    title: "Boyfriend",
    released: 2012,
    duration: 157,
    url: "https://www.youtube.com/watch?v=4GuqB1BQVr4",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-014",
    artistId: "AID-000003",
    title: "Beauty and a Beat",
    released: 2012,
    duration: 231,
    url: "https://www.youtube.com/watch?v=Ys7-6_t7OEQ",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-015",
    artistId: "AID-000003",
    title: "Hold On",
    released: 2021,
    duration: 174,
    url: "https://www.youtube.com/watch?v=L8eRzOYhLuw",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-016",
    artistId: "AID-000003",
    title: "As Long As You Love Me",
    released: 2012,
    duration: 238,
    url: "https://www.youtube.com/watch?v=R4em3LKQCAQ",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-017",
    artistId: "AID-000003",
    title: "Somebody",
    released: 2021,
    duration: 186,
    url: "https://www.youtube.com/watch?v=jLQrk6rmX6w",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-018",
    artistId: "AID-000003",
    title: "Mistletoe",
    released: 2011,
    duration: 214,
    url: "https://www.youtube.com/watch?v=LUjn3RpkcKY",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-019",
    artistId: "AID-000003",
    title: "No Brainer",
    released: 2018,
    duration: 260,
    url: "https://www.youtube.com/watch?v=kX7mA0sbkx8",
    isExplicit: true,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
  {
    songId: "SID-020",
    artistId: "AID-000003",
    title: "Where Are Ü Now",
    released: 2015,
    duration: 240,
    url: "https://www.youtube.com/watch?v=webUeq_Qzeg",
    isExplicit: false,
    imageUrl: "./image/justin-bieber-song.jpg",
  },
];
